# -*- coding: utf-8 -*-
"""introducao-python-exercicios.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/mariavaicomasdevs/introducao-python/blob/main/introducao_python_exercicios.ipynb

---
### Tipado Dinamicamente

Python é uma linguagem tipada dinalicamente, ou seja,  não é necessário declarar uma variável e definir o tipo de seu dado: o tipo de dado será associado em tempo de execução de acordo com o valor atribuído para aquela variável. 

### Tipos básicos  

O Python possui algunas funçoes nativas, chamadas de "built-ins"que nos ajudam na manipulação de strings

|Python | O que significa  | Exemplos  | 
|:---:|:---|:---|
| bool     | Valores booleanos: Verdadeiro ou Falso | eh_maior = 22 > 10 <br> status = False
| float     | Valores com ponto flutuante |  nota = 7.5 <br> preco = 30.55 
| int| Valores inteiros: …, -2, -1, 0, 1, 2, 3, ... |  alunos_presentes = 20 <br> numero_de_slides = 50
| str     | Textos: python considera texto tudo que estiver entre aspas (simples ou duplas)        | dia = "sábado" <br> assunto = 'python  básico' <br> semana = "5"
| Lista   | Sequência de objetos separados por vírgula, e dentro de colchetes.  | devs = ["ana", "amanda, "andorinha"] <br> idades = [23, 19, 38]

Execute os comandos de exemplo para visualizar os resultados:
"""



"""### Variáveis

Em Python os nomes das variáveis podem ser compostos de letras maiúsculas, minúsculas, underscore e números, iniciando com letras ou underscore (_).


### Tipagem das variáveis

Há um comando para descobrir o tipo de uma variável: type().

Exemplo:
```
nome = "Alini"
valor = 10
expressao = 1 + valor / 3

print(nome)
print(valor)
print(expressao)

print(type(nome))
print(type(valor))
print(type(expressao))
``` 
Execute os comandos de exemplo para visualizar os resultados:
"""



"""---

### Exercícios Python [1]
Você possui uma variável a = 10 e uma variável b = 5, e precisa trocar o valor das duas. Como você faria?
"""



"""---
### Entradas e saídas

Perceberam que no exercício anterior eu utilizei uma função chamada print, para apresentar a informação da variável na tela?
Print é uma função de saída, e também possuímos uma função de entrada, chamada input.
```
Entrada: 
	input(“Texto opcional que será exibido para o usuário”)
Saída:
	print(f"Textos a serem exibidos e {variaveis}")
```
**Os textos devem ser colocados entre aspas.

### Exercícios Python [2]
Faça um programa que pergunte que dia é, e diga quantos faltam até o final do mês. Considere o mês com trinta e um dias.
"""

date = int(input("Qual a dia de hoje?"))
data = 31 - date
print(f"Faltam  {data} para o fim mes")

"""--------------------------------------------------------------------------------
### Exercícios Python [3]

Faça um programa que receba o número de brindes do Maria vai com as Devs que  a Jéssica vai mandar fazer, e imprima quanto de entrada ela irá que pagar. Considere que cada brinde custa R$25,00, e a entrada para o fabricante é de 50% do valor total.
"""

valor =25
qtd = int(input("Digite a quantidade de brindes"))
total = (valor*qtd)/2
print(f"O valor da entrada será de: {total}")

"""---

### Exercícios Python [4]
A Serasa irá gerar um minicurso de aprendizagem financeira e está planejando um coffee break ás 15 horas.

Leia o número de participantes do minicurso e imprima: 
* Quantos litros de refrigerante teremos que comprar
* Quantas coxinhas e quanto iremos gastar.

Considere que cada participante toma 400ml de refrigerante, come 10 coxinhas, que cada litro de refrigerante custa 4,00 e cada coxinha  custa  0,50.
"""

participantes = int(input("Digite quantas pessoas participarão do coffee break"))
refri = int(0.4*participantes)
salgado = (10*participantes)
valor_refri = (refri*4)
valor_salgado = (salgado*0.50)
total = (valor_refri+valor_salgado)

print(f"o Total de participantes é de {participantes} pessoas. Serão necessário {salgado} unidades de salgados e {refri} litros de refrigerante.")
print(f'O total gaasto será de {total:.2f} reais')

"""----
### Dicas [Comentários]
"""

print("Exemplo de código que não vai ser ignorado pelo Python")
#Comentário que o Python não vai processar ^-^

"""---
### Dicas [Incremento e Decremento]

No Python você pode incrementar ou decrementar um valor e salvar o resultado na mesma variável.
"""



"""---
### Dicas [Separando um texto com split()]

Se você não determinar nenhum caractere de espaçamento para o split(), ele assumirá que é um espaço em branco.
Como você dividirá sua entrada em duas, poderá armazená-la em duas variáveis diferentes! Se você não colocar variáveis suficientes, python criará uma lista*.
"""



"""---- 
#### Dicas [Separando um texto com split()]
Na conversão de tipos de dados de entrada, para dividir a entrada em mais de uma variável e já transformar ela para o tipo desejado, utilizamos um comando auxiliar chamado map()
"""



"""---
### Exercícios Python [5]

Para que a jéssica consiga enviar os brindes e não errar na preferência de cores de todas as participantes, ela precisa saber a quantidade de pessoas que preferem a cor rosa, roxo ou azul.
Faça um programa que leia a quantidade de pessoas que preferem cada cor e retorne a porcentagem de cada uma destas cores.
"""



"""---
### Estruturas condicionais

Uma Estrutura de Condição, como o próprio nome já diz, verifica a condição dos argumentos passados e, executa um comando caso a condição seja verdadeira.

```
SE condição
ENTÃO comando
```

Sintaxe em python:
```
if condição:
    código
elif condição:
    código
else:
    código
```

### Exercícios Python [6]

Dez pessoas assinalaram que iriam participar do encontro do Maria vai com as Devs hoje. 

Faça um programa que leia o número de pessoas presentes e escreva “Sucesso!” se todas as pessoas compareceram, e “Alguém faltou :/” caso contrário.

Se houverem mais de dez pessoas imprima “Temos um intruso entre nós :v”.
"""



"""---
### Álgebra booleana em Python
Para facilitar a estruturação das condições, podemos utilizar os operadores booleanos

| Operador  | Python | Exemplo  | Descrição  |
|---|:---|:---|:---|
| E| and|P and Q |Se P e Q forem verdadeiros retorna True, se não retorna False 
|OU| or|P or Q|Se P ou Q forem verdadeiros retorna True, se não retorna False
|Não  | not | not Q |Se Q é verdadeiro retorna False, se não retorna True
"""

a = True
b = False
c = None 

# Retorna True, porque o c é None, ou seja, não á valor nenhum atribuído a ele
print(f"Condicional not (not c): {not c}")

#Retorna True, porque o a é verdadeiro. Para retornar True, uma das opções deve ser verdadeira
print(f"Condicional or (a or b): {a or b}")

#Retorna False, porque o a é verdadeiro e o b é False. Para retornar True, ambos devem ser verdadeiros
print(f"Condicional and (a and b): {a and b}")

"""---
### Exercícios Python [7]
Receba duas notas, uma é de uma prova e outra é de um trabalho, por fim retorne:

Se a nota da prova for maior ou igual a 5 e nota do trabalho maior que 6: “Aprovado”;
Senão: “Reprovado”.
"""



"""---
### Exercícios Python [8]

A Serasa anualmente promove a ida dos desenvolvedores para a Python Brasil, mas como temos um número limitado de ingressos disponíveis, pode ser necessário decidir quem irá.

Como critério de desempate sobre os ingressos, quem nunca participou do evento terá prioridade.

Receba o número de ingressos disponíveis, o número total de interessados e o número de interessados que já participaram do evento antes, diga se é possível distribuir os ingressos apenas com essas regras, ou se será necessário um sorteio.
"""



"""---
### Exercícios Python [9]

Nos últimos anos o Brasil está com muita variação de temperatura, e uma coisa louca acontecendo é que você pode passar por várias estações do ano num mesmo dia!
Para ajudar as pessoas a não pegar uma gripe ou uma insolação, você vai ler a temperatura e a umidade do ar da tabela a seguir,e criar um programa que classifica quais itens de sobrevivência são necessários para nossos dias de “verão”.

| Temperatura às 8h - ºC  |  Umidade do ar - % | Itens de sobrevivência  |
|---|---|---|
| 10ºC < 15ºC  | 0 <= 40    | Blusa de frio e regata                |
| 10ºC < 15ºC  | 40 <= 100 | Blusa de frio, regata e guarda-chuva  |
| 15ºC < 20ºC  | 0 < 40    | Blusa de frio e regata                |
| 15ºC < 20ºC  | 40 <= 100 | Blusa de frio, regata e guarda-chuva  |
| 20ºC < 25ºC  | 0 < 40    | Regata                                |
| 20ºC < 25ºC  | 40 <= 100 | Regata e guarda-chuva                 |
"""



"""---
###  Strings [Símbolos]

O Python possui alguns símbolos que nos auxiliam na manipulação de strings:


|Símbolo | Signficado  | Exemplo  | Resultado  | 
|:---:|:---|:---|:---:|
| +      | Concatenação  |  'bolinho de ' + 'chuva '+ 'quero' | ?  |
| -      | Repetição     |  'Maria vai com as devs '*4        | ?  |
|[]      | Indexação     |  'chuva'[1]                        | ?  |
|[:]     | Fatiamento    |  'chuva'[0:1]                      | ?  |
|{}      | Substituição  |  'chuv{}'.format('inha')           | ?  |
|in      | Verificação   |  'chuv' in 'chuvinha'              | ?  |
|not in  | Verificação   |  'chuva' not in 'chuvinha'         | ?  |



Execute os comandos de exemplo para visualizar os resultados:
"""

'chuv{}'.format('inha')

"""---

### Strings [Funções]  

O Python possui algunas funçoes nativas, chamadas de "built-ins"que nos ajudam na manipulação de strings

|Função | Parâmetro  | Aplicação  | Resultado  | 
|:---:|:---|:---|:---:|
| upper     | nenhum      |  "bolinho de chuva".upper()              | ?  |
| lower     | nenhum      |  "BOLINHO DE CHUVA".lower()              | ?  |
| capitalize| nenhum      |  "bolinho de chuva".capitalize()         | ?  |
| count     | item        |  "bolinho de chuva".count("h")           | ?  |
| replace   | (old, new)  |  "bolinho de chuva".replace("a", "inha") | ?  |
| find      | item        |  "bolinho de chuva".find("chu")          | ?  |
| len       | item        |  len("bolinho de chuva")                 | ?  |










Execute os comandos de exemplo para visualizar os resultados:
"""

len("bolinho de chuva")

"""---
### Exercícios Python [10]

Você é o responsável por gerar os certificados dos da trilha financeira da serasa, porém, sabemos que eventualmente os participantes não cooperam e escrevem seus nomes sem seguir a norma padrão, apenas com a primeira letra maiúscula. Para evitar certificados despadronizados, você resolveu escrever um programa em Python para normalizar os nomes para você!

O programa recebe um nome e padroniza o nome para você:
"""



"""---
### Estruturas de repetição

As estruturas padrões para repetição em Python são:
 ```
 while (condição):
    # código
 ``` 

 ```
 for item in iterável:
  # código
```  

### Exercício Python[11]

Leia números enquanto a soma dos números lidos seja menor que 20.
"""



"""---
### Exercicio Pyhton [12]
Possuímos uma lista de cinco desenvolvedoras que participam do programa Maria vai com as devs. Elas se chamam: Andorinha, Azaléia, Amélia, Margarida e Rosa.

Construa um programa que descubra quantas delas possuem o nome começando com a letra “A”.
"""

